ELearningSystem/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ELearningSystem.Services;
using ELearningSystem.Model;
using Ninject.Activation;

namespace ELearningSystem.Controllers
{
    public class TestsController : Controller
    {
        private const string TESTKEY = "TESTKEY";
        private const string COURSEKEY = "COURSEKEY";
        List<Test> testModel = new List<Test>();
        private const int TESTQUESTIONSCOUNT = 10;
        public Test CurrentTest
        {
            get
            {
                return Session[TESTKEY] as Test ?? new Test();
            }
            set
            {
                Session[TESTKEY] = value;
            }
        }

        public Student User
        {
            get
            {
                return Session["USER"] as Student;
            }

            set
            {
                Session["USER"] = value;
            }
        }


        private TestService testService = new TestService();
        private CourseService courseService = new CourseService();

        public ActionResult Index(int id = 0)
        {
            if (id != 0)
            {
                var testModel = testService.GetTest(id);
                List<Test> tests = testService.GetAllTests(id);
                if (tests.Count() > 0)
                {
                    return AllTests(tests);
                }
                else
                {
                    if (testModel != null)
                    {
                        testModel.Questions = testService.GetTestQuestions(testModel.Id);
                        foreach (var question in testModel.Questions)
                        {
                            question.Answers = testService.GetQuestionAnswers(question.Id);
                        }

                        CurrentTest = testModel;

                        return View(testModel);
                    }
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult AllTests(List<Test> tests)
        {
            return View("AllTests",tests);
        }


        [HttpPost]
        public ActionResult SubmitTest(Model.Test test)
        {
            int correctAnswers = GradeTest(test);
            var testResult = new TestResult();


            DateTime date = DateTime.Now; // will give the date for today
            string dateWithFormat = date.ToLongDateString();
            testResult.Date = DateTime.Now;
            testResult.CorrectAnswers = correctAnswers;
            testResult.EmptyAnswers = EmptyAnswers(test);
            testResult.WrongAnswers = TESTQUESTIONSCOUNT - (testResult.EmptyAnswers + correctAnswers);
            testResult.Procent = correctAnswers * 10;
            if (correctAnswers <= 2)
            {
                testResult.Status = "Bad";
                testResult.Grade = "Слаб(2)";
            }
            else if (correctAnswers <= 4)
            {
                testResult.Status = "Bad";
                testResult.Grade = "Среден(3)";
            }
            else if (correctAnswers <= 6)
            {
                testResult.Status = "Good";
                testResult.Grade = "Добър(4)";
            }
            else if (correctAnswers <= 8)
            {
                testResult.Status = "Excellent";
                testResult.Grade = "Много добър(5)";
            }
            else
            {
                testResult.Status = "Excellent";
                testResult.Grade = "Отличен(6)";
            }
            testService.InsertResult(test.Id, User.Id, testResult.Grade);
            return View("TestResult", testResult);
        }

        private int GradeTest(Test test)
        {
            int countRightAnswers = 0;
            int countWrongAnswers = 0;
            if (test.Questions == null)
                return 0;
            for (int i = 0; i < test.Questions.Count(); i++)
            {
                if (test.Questions[i].Answer == 0)
                {
                }
                else if ((test.Questions[i].Answer - 1) == CurrentTest.Questions[i].RightAnswerIndex)
                {
                    countRightAnswers++;
                }
                else
                {
                    countWrongAnswers++;
                }
            }
            return countRightAnswers;
        }

        private int EmptyAnswers(Test test)
        {
            int countEmptyAnswers = 0;
            if (test.Questions == null)
                return 0;
            for (int i = 0; i < test.Questions.Count(); i++)
            {
                if (test.Questions[i].Answer == 0)
                {
                    countEmptyAnswers++;
                }
            }
            return countEmptyAnswers;
        }
    }
}

ELearningSystem/Views/Tests/AllTests.cshtml
@model IEnumerable<ELearningSystem.Model.Test>
@{
    ViewBag.Title = "AllTests";
    int i = 0;
}

<h2>@Resources.Resource.strTests</h2>

<div style="display: inline-block; padding-top:20px">

    @foreach (var item in Model)
    {
        <div class="test-icon">
            @*<li>@Html.ActionLink(item.Title, "Index", "Tests", new {item.Id}, null)</li>*@
            <a href="@Url.Action( "Index", "Tests", new {item.Id}, null)">
                <img src="~/Images/testicon.jpg" style="height:70px" />
                <p>@item.Title</p>
            </a>
        </div>
        i++;
        if (i % 3 == 0)
        {
            <br />

        }
    }
</div>

ELearningSystem/Views/Tests/Index.cshtml
@model ELearningSystem.Model.Test
@{
    ViewBag.Title = "Index";
}

@if (Model != null)
{
    using (Html.BeginForm("SubmitTest", "Tests", FormMethod.Post))
    {
        <text>Тест: </text>
        @Html.DisplayFor(m => m.Title)
        @Html.HiddenFor(m => m.Id)
    
        <div>
            <ul>
                @for (var i = 0; i < Model.Questions.Count; i++)
                    {
                    @Html.Partial("_Question", new { index = i, question = Model.Questions[i] })
                    }
            </ul>
        </div>
    <input type="submit" value=@Resources.Resource.strCheck />
    }
}

ELearningSystem/Views/Tests/TestResult.cshtml
@model ELearningSystem.Model.TestResult
@{  var gifPath = "";
  gifPath = String.Format(@"../Content/{0}.gif", @Model.Status);
  var imagePath = "";
  if (@Model.Procent <= 20)
  { imagePath = String.Format(@"../Content/{0}.png", "Poor2"); }
  else if (@Model.Procent <= 40)
  { imagePath = String.Format(@"../Content/{0}.png", "Middle3"); }
  else if (@Model.Procent <= 60)
  { imagePath = String.Format(@"../Content/{0}.png", "Good4"); }
  else if (@Model.Procent <= 80)
  { imagePath = String.Format(@"../Content/{0}.png", "VeryGood5"); }
  else
  { imagePath = String.Format(@"../Content/{0}.png", "Excellent6"); }
}
<div>
    @Resources.Resource.strCorrectAnswers @Model.CorrectAnswers
</div>
<div>
    @Resources.Resource.strWrongAnswers @Model.WrongAnswers
</div>
<div>
    @Resources.Resource.strEmptyAnswers @Model.EmptyAnswers
</div>
<div>
    @Resources.Resource.strProcent @Model.Procent %
</div>
@*<div>
        @Html.Partial("_Chart")
    </div>*@
<div>
    @Resources.Resource.strGrade
    <img id="image" src="@imagePath" height="60" width="100" />
</div>
<div style="float: right; height: 120px; width: 400px; ">
    <img id="image" src="@gifPath" />
</div>

ELearningSystem/Views/Tests/_Answer.cshtml
@model object

@{
    dynamic mod = Model;
    var answer = mod.GetType().GetProperty("answer").GetValue(mod, null) as ELearningSystem.Model.Answer;
    var questionIndex = (int)mod.GetType().GetProperty("questionIndex").GetValue(mod, null);
    var answerIndex = (int)mod.GetType().GetProperty("answerIndex").GetValue(mod, null);
}
<div>
    @*@Html.RadioButton(string.Format("Qustions[{0}].Answer", questionIndex), false, false, new { data })*@

    <input type="radio" data-index="@answerIndex" />
    @Html.Label(answer.Content)
</div>

ELearningSystem/Views/Tests/_Chart.cshtml
@model ELearningSystem.Model.TestResult
@{
    var myChart = new Chart(width: 300, height: 150)
        .AddTitle("Диаграма на отговори на теста")
        .AddSeries(
            name: "TestResult",
            xValue: new[] { "Верни отговори", "Грешни отговори", "Непопълнени отговори" },
            yValues: new[] { Model.CorrectAnswers, Model.WrongAnswers, Model.EmptyAnswers })
        .Write();
}
<div>
    <img src="@Url.Action("StatusGraph", new { Model = @Model })" />
</div>

ELearningSystem/Views/Tests/_Question.cshtml
@model object

@{
    dynamic mod = Model;
    var question = mod.GetType().GetProperty("question").GetValue(mod, null) as ELearningSystem.Model.Question;
    var questionIndex = Convert.ToInt32(mod.GetType().GetProperty("index").GetValue(mod, null));
}
<div class="question">
    <p>@question.Content</p>
    <input type="hidden" name="Questions[@questionIndex].Answer" value=""/>
    <div>
        <ul>
            @for (var i = 0; i < question.Answers.Count; i++)
            {
                @Html.Partial("_Answer", new { answerIndex = i+1, questionIndex = questionIndex, answer = question.Answers[i] })
            }
        </ul>
    </div>
</div>